[package]
name = "usbmaker"
version = "2.0.0"
authors = ["Joaquim Monteiro <joaquim.monteiro@protonmail.com>"]

[dependencies]
ansi_term = "0.11"
clap = "2"
indicatif = "0.9"
libparted = "0.1"
tempfile = "3"

[profile.release]
codegen-units = 1
lto = true
