# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(363, 454)
        MainWindow.setMinimumSize(QtCore.QSize(363, 0))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_device = QtWidgets.QLabel(self.centralWidget)
        self.label_device.setTextFormat(QtCore.Qt.PlainText)
        self.label_device.setObjectName("label_device")
        self.verticalLayout.addWidget(self.label_device)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_device = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_device.sizePolicy().hasHeightForWidth())
        self.comboBox_device.setSizePolicy(sizePolicy)
        self.comboBox_device.setObjectName("comboBox_device")
        self.horizontalLayout_4.addWidget(self.comboBox_device)
        self.pushButton_refresh = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_refresh.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout_4.addWidget(self.pushButton_refresh)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_partscheme = QtWidgets.QLabel(self.centralWidget)
        self.label_partscheme.setTextFormat(QtCore.Qt.PlainText)
        self.label_partscheme.setObjectName("label_partscheme")
        self.verticalLayout.addWidget(self.label_partscheme)
        self.comboBox_partscheme = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_partscheme.setObjectName("comboBox_partscheme")
        self.verticalLayout.addWidget(self.comboBox_partscheme)
        self.label_filesystem = QtWidgets.QLabel(self.centralWidget)
        self.label_filesystem.setTextFormat(QtCore.Qt.PlainText)
        self.label_filesystem.setObjectName("label_filesystem")
        self.verticalLayout.addWidget(self.label_filesystem)
        self.comboBox_filesystem = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_filesystem.setObjectName("comboBox_filesystem")
        self.verticalLayout.addWidget(self.comboBox_filesystem)
        self.label_label = QtWidgets.QLabel(self.centralWidget)
        self.label_label.setTextFormat(QtCore.Qt.PlainText)
        self.label_label.setObjectName("label_label")
        self.verticalLayout.addWidget(self.label_label)
        self.lineEdit_label = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_label.setObjectName("lineEdit_label")
        self.verticalLayout.addWidget(self.lineEdit_label)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_formatoptions = QtWidgets.QLabel(self.frame)
        self.label_formatoptions.setTextFormat(QtCore.Qt.PlainText)
        self.label_formatoptions.setObjectName("label_formatoptions")
        self.verticalLayout_3.addWidget(self.label_formatoptions)
        self.checkBox_checkbadblocks = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_checkbadblocks.setFont(font)
        self.checkBox_checkbadblocks.setObjectName("checkBox_checkbadblocks")
        self.verticalLayout_3.addWidget(self.checkBox_checkbadblocks)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_bootmethod = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_bootmethod.setFont(font)
        self.checkBox_bootmethod.setChecked(True)
        self.checkBox_bootmethod.setObjectName("checkBox_bootmethod")
        self.horizontalLayout_3.addWidget(self.checkBox_bootmethod)
        self.comboBox_bootmethod = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_bootmethod.setFont(font)
        self.comboBox_bootmethod.setObjectName("comboBox_bootmethod")
        self.horizontalLayout_3.addWidget(self.comboBox_bootmethod)
        self.pushButton_filedialog = QtWidgets.QPushButton(self.frame)
        self.pushButton_filedialog.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_filedialog.setObjectName("pushButton_filedialog")
        self.horizontalLayout_3.addWidget(self.pushButton_filedialog)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_status = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setText("")
        self.label_status.setTextFormat(QtCore.Qt.PlainText)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_2.addWidget(self.label_status)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_about = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_about.setObjectName("pushButton_about")
        self.horizontalLayout.addWidget(self.pushButton_about)
        spacerItem = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(64, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(69, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_start = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout.addWidget(self.pushButton_start)
        spacerItem3 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_close = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "USBMaker"))
        self.label_device.setText(_translate("MainWindow", "Device"))
        self.pushButton_refresh.setText(_translate("MainWindow", "⟳"))
        self.label_partscheme.setText(_translate("MainWindow", "Partition scheme and target system type"))
        self.label_filesystem.setText(_translate("MainWindow", "File system"))
        self.label_label.setText(_translate("MainWindow", "New volume label"))
        self.label_formatoptions.setText(_translate("MainWindow", "Format Options"))
        self.checkBox_checkbadblocks.setText(_translate("MainWindow", "Check device for bad blocks"))
        self.checkBox_bootmethod.setText(_translate("MainWindow", "Create a bootable disk using"))
        self.pushButton_filedialog.setText(_translate("MainWindow", "..."))
        self.pushButton_about.setText(_translate("MainWindow", "About..."))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_close.setText(_translate("MainWindow", "Close"))

